Props
htmlacademy-react/1333325-six-cities-9 pull request #3
Opened 2022-03-06 20:38 UTC by AzisHop

2022-03-07 09:25 UTC, bini1988 requested changes
- Нужно вынести svg спрайт в index.html
- Избавиться от index.tsx переименовав файлы компонентов
- В техническом задании указ списко страниц приложения:
  > Приложение состоит из нескольких страниц: Main (/), Sign In (/login), Favorites (/favorites) (приватная), Room (/offer/:id).
  Нужно избавиться от лишних страниц `favorites` и `main` поскольку это не отдельные страницы, а состояния страниц `favorites` и `main`
- Не выполнена часть ДЗ  
  > Создайте в директории /src/components отдельный компонент для отображения одной карточки предложения в списке. Перенесите в него соответствующую часть разметки из компонента, созданного в первом шаге.

  > Удалите из компонента созданного в первом шаге все статичные карточки предложений. Вместо них, подключите компонент карточки предложения и выведите его столько раз, сколько было предусмотрено карточек предложений в изначальной разметке.
  > Теперь, используя props, добавим динамики в компоненты. Для этого в компоненте главной страницы приложения определите изменяемые данные — это будет количество предложений аренды. Получите их из props и вставьте в JSX компонента.

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/favorites-empty/index.tsx
> +      </div>
Это часть [svg спрайта](http://dreamhelg.ru/2017/02/symbol-svg-sprite-detail-guide/) с иконками проекта,  я бы предложил оставить эту верстку в index.html. Если в index.html уже есть аналогичный блок верстки, то иконку необходимо объеденить в один облок.

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/favorites/index.tsx
> +      </div>
Вынести в index.html

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/login/index.tsx
> +      </div>
Вынести в index.html

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/main-empty/index.tsx
> +      </div>
Вынести в index.html

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/favorites-empty/index.tsx
> +export default function FavoritesEmpty(): JSX.Element {
По критериям в проекте должен быть только один `index.ts` файл, файл компонента должен совпадать с его именем `favorites-empty.tsx`

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/favorites-empty/index.tsx
> +export default function FavoritesEmpty(): JSX.Element {
Кажется это страница дублирует `favorites`

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/main-empty/index.tsx
> +export default function MainEmpty(): JSX.Element {
А эта страница дублирует `main`

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/main/index.tsx
> +export default function Main({place} : MainPageProps): JSX.Element {
Я бы предложил одинаковое именовани типов и компонента `Main` `MainProps` или `MainPage` `MainPageProps`, плюс имя компонента должно совпадать с именем файла

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/property/index.tsx
> +      </div>
Вынести в index.html

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/property-not-logged/index.tsx
> +      </div>
Вынести в index.html

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/property-not-logged/index.tsx
> +export default function PropertyNotLogged(): JSX.Element {
Кажется `PropertyNotLogged` и `Property` тоже дублируют друг друга

2022-03-07 09:25 UTC, bini1988 commented on project/src/pages/main/index.tsx
> +      <div className="page page--gray page--main">
Вынести в index.html

2022-03-07 09:27 UTC, bini1988 commented
![image](https://user-images.githubusercontent.com/8654155/157003970-f60056b0-7b29-4da2-bc7a-7c6c14569324.png)

Для мержа ПР необходимо чтобы все чеки были зелеными

2022-03-07 09:29 UTC, bini1988 commented on project/package.json
> +    "lint": "eslint --ext .tsx --ext .ts src/ --fix"
Эта комманда запусткается в CI, давай оставим ее как есть, но можно добавить свою собсвтенную комманду `"lint-fix": "eslint --ext .tsx --ext .ts src/ --fix"`

2022-03-14 21:16 UTC, AzisHop commented
Все поправил + разбил на компоненты страницы. Страницу "Room" буду более тщательно разбивать при написании обработчиков.

2022-03-15 19:28 UTC, bini1988 requested changes
Давай поправим замечания и зальем этот ПР, а новый функционал уже в новом ПР отправишь

2022-03-15 19:28 UTC, bini1988 commented on project/src/components/room-gallery/roomGallery.tsx
> +  let imgId = 0;
А что мешает использовать index который пердает в колбэк map ?

2022-03-15 19:28 UTC, bini1988 commented on project/src/pages/main/main.tsx
> +  place: number;
А почему здесь `place` типа `number`? Я бы ожидал что здесь ожидается объект предложения.

2022-03-15 19:28 UTC, bini1988 commented on project/src/pages/room/Room.tsx
> +  const data2: Hotel = hotel;
Слодно по названию переменной `data2` сказать для чего она тут нужна

2022-03-15 19:28 UTC, bini1988 commented on project/src/pages/room/Room.tsx
> +  const places = placesNearby.map(({
А здесь еще приходится искать гже же используется переменная  `places`

2022-03-15 19:28 UTC, bini1988 commented on project/src/types/types.ts
> +export interface CitiesFavorites {
Это тип можно записать как `type CitiesFavorites = Record<Cities, PlaceType[]>`

2022-03-15 19:28 UTC, bini1988 commented on project/src/utils/utils.ts
> +  switch (Math.round(rating)) {
У же отмечал, тут умесней математические вычесления

2022-03-15 19:28 UTC, bini1988 commented on project/src/pages/favorites/favorites.tsx
> +import {favoritesPage} from '../../mock/favoritesMock';
[Б19.](https://up.htmlacademy.ru/react/9/criteries#b19) Все компоненты находятся в папке src/components

Нужно поправить для всего проекта

2022-03-16 17:44 UTC, AzisHop commented on project/src/components/comments/comments.tsx
> +  ));
Для меня, на самом деле, наоборот проще для восприятия такой код, то есть когда ts (js) код отделен от основной разметки React, что делает его намного проще для восприятия. Такой же подход видел в разных проектах. Тут скорее всего дело вкуса)

2022-03-16 19:07 UTC, bini1988 commented on project/src/components/comments/comments.tsx
> +  ));
Не совсем понимаю что значит `когда ts (js) код отделен от основной разметки React`?  Разметка React это посути и есть js код, это не html или ему подобное, это просто синтаксический сахар над js который превращается в итого в вызовые стандартных js функций, мешать jsx с обычным js вполне номальная практика. 

Если всетаки хочется разделять логику то можно вынести генерацию списка в отдельный компонент:

```tsx
const CommentsList ({comments}) => comments.map(({
    comment,
    date,
    id,
    rating,
    user,
  }) => (
    <Comment
      key={id}
      comment={comment}
      date={date}
      id={id}
      rating={rating}
      user={user}
    />
  ));



 <ul className="reviews__list">
        <CommentsList comments={comments}/>
  </ul>
```

2022-03-16 19:27 UTC, AzisHop commented on project/src/types/types.ts
> +export interface PlaceType {
Просто Place не получится, потому что так называется компонент и идет пересечение названий

2022-03-16 19:37 UTC, AzisHop commented on project/src/types/types.ts
> +export interface CommentType {
тоже, что и с Place, поменя "Type" на "Data"

2022-03-17 11:32 UTC, AzisHop commented on project/src/components/room-gallery/roomGallery.tsx
> +  let imgId = 0;
Линтер :)

2022-03-17 11:50 UTC, AzisHop commented on project/src/components/comments/comments.tsx
> +  ));
"Разметка React это посути и есть js код, это не html или ему подобное, это просто синтаксический сахар над js" это понятное дело, я говорил как раз об разделение основной разметки (обертки React над языком) и чистых языковых конструкций, насколько это возможно. Это позволяет привести основную разметку j(t)sx максимально к похожей на простой html, что на мой взгляд упрощает восприятие. А новый компонент я не стал делать, чтобы не плодить "лишние" компоненты. Насчет "мешать jsx с обычным js вполне номальная практика" полностью согласен, часто вижу такой код. Но и свой вариант я тоже видел в проектах, просто мне он ближе оказался. Если что, я поправил код на твой вариант)

2022-03-17 11:56 UTC, AzisHop commented on project/src/pages/main/main.tsx
> +  place: number;
Я бы вообще отсюда пропсы убрал, но в ТЗ к этому ДЗ надо передать кол-во количество предложений аренды (place). В будущих ПРах собираюсь убрать это, так как буду получать с сервера всю инфу, а кол-во предложений - это длина массива

2022-03-17 11:56 UTC, AzisHop commented on project/src/components/place/place.tsx
> +import cn from 'classnames/bind';
Да, тут какая-то заминка произошла и он фиг знает куда установился, поправил

2022-03-17 12:06 UTC, AzisHop commented on project/src/components/favorites-places/favoritesPlaces.tsx
> +  for (const amount of cities.values()) {
Сходу не получится, потому что values() не массив вернет, поэтому метод map не сработает. Тут придется либо так делать "Array.from(map.values())", либо через for. Через for мне кажется поприятнее

2022-03-17 12:18 UTC, AzisHop commented on project/src/types/types.ts
> +export interface Hotel {
Оставил только Hotel

2022-03-17 14:54 UTC, bini1988 approved these changes

2022-03-17 14:54 UTC, bini1988 commented on project/src/types/types.ts
> +export interface Hotel {
Еще немного позанудствую, я бы предпочел не плодить сущности в проекте без необходимости, если выбрал `Place` то использовать его и типах и в переменных, иначе появляются вопросы к коду вида:

```ts
interface FavoritesPlacesProps {
  favoritesPlaces: Hotel[]
}
```

Лишние синонимы в коде имхо в данном случае лишь забивают оперативку.

2022-03-17 14:56 UTC, merged