Map Done
htmlacademy-react/1333325-six-cities-9 pull request #5
Opened 2022-04-05 11:40 UTC by AzisHop

2022-04-06 10:00 UTC, bini1988 requested changes
Есть несколько критичных замечаний, предлагаю их поправить, потом пойти дальше

2022-04-06 20:34 UTC, AzisHop commented on project/src/components/header/header.tsx
> +                        <Link className="header__nav-link" to={page} onClick={handleClickSign}>
Выше был согласен, было лишним. Здесь же нужно обработать событие выхода и в "to" это положить не получится, но в то же время заменить "to" на onClick тоже нельзя, так как это является обязательным параметром. Пока что тогда повесил это событие на родительский блок <li>, чтобы не сбивало с толку.

2022-04-07 11:45 UTC, AzisHop commented on project/src/types/types.ts
> +    },
Да, приходят, но рациональнее забить эти данные в массив, потому что с сервера приходит огромный массив со всеми местами и искать в нем город не особо рационально. Нужный город может находится далеко от начала пришедшего массива, поэтому по производительности выгоднее вариант с заранее подготовленным маленьким массивом городов. Ну, а данные городов все равно не меняются, следовательно  являются константой и не могут отличаться от данных с сервера.

2022-04-07 11:56 UTC, bini1988 commented on project/src/types/types.ts
> +    },
В теории достаточно один раз пройтись по этому массиву чтобы собрать список униакальных городов и их местоположение.

> Ну, а данные городов все равно не меняются, следовательно являются константой и не могут отличаться от данных с сервера.

Ну так там все данные статические и не меняются, почему их тогда не хранить на клиенте?

2022-04-07 12:04 UTC, bini1988 approved these changes

2022-04-07 12:04 UTC, merged